[bar.default]
background_opacity = 0.80
center = [ "workspaces" ]
end = [
    "media",
    "spacer",
    "tray",
    "notifications",
    "clipboard",
    "network",
    "bluetooth",
    "volume",
    "brightness",
    "battery",
    "clock",
    "session"
]
font_weight = 700
margin_ends = 0
radius = 0
shadow = false
start = [ "active_window" ]
thickness = 32

[lockscreen_widgets]
enabled = false

[shell]
corner_radius_scale = 0.0
settings_show_advanced = false

    [shell.panel]
    control_center_placement = "floating"
    control_center_position = "top_left"
    open_near_click_control_center = true

[theme]
builtin = "Tokyo-Night"
community_palette = "Oxocarbon"
mode = "dark"
source = "builtin"
wallpaper_scheme = "m3-content"

[widget.Spacer]
type = "spacer"

[widget.active_window]
display = "text_only"
max_length = 600

[widget.media]
hide_album_art = true
hide_when_no_media = true
max_length = 800

[widget.network]
show_label = false

[widget.spacer]
type = "spacer"

[widget.workspaces]
style = "minimal"
